apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: mlperf
  name: mlperf-maskrcnn-1.1-dell
  namespace: default
spec:
  output:
    to:
      kind: ImageStreamTag
      name: mlperf:maskrcnn_1.1_dell
      namespace: default
  resources: {}
  source:
    type: Git
    git:
      uri: "https://github.com/mlcommons/training_results_v1.1"
      ref: "main"
    contextDir: Dell/benchmarks/maskrcnn/implementations/pytorch
  triggers:
  - type: "ConfigChange"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: DockerImage
        name: nvcr.io/nvidia/pytorch:21.09-py3
