apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-burn-entrypoint
  namespace: default
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e

    cd /tmp
    SRC=https://raw.githubusercontent.com/kpouget/gpu-burn/master
    for f in  compare.cu  gpu_burn-drv.cpp Makefile; do
      curl -s $SRC/$f > $f
    done

    make
    date
    echo ""
    time /tmp/gpu_burn $GPU_BURN_TIME
