apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-mig-mode
  namespace: gpu-operator-resources
data:
  nva100_mig-parted_config.yaml: |
    version: v1
    mig-configs:
      all-full:
        - devices: all
          mig-enabled: false

      all-1g.5gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 7

      all-2g.10gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.10gb": 3

      all-3g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "3g.20gb": 2

      all-4g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "4g.20gb": 1

      all-7g.40gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.40gb": 1

      all-balanced:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 2
            "2g.10gb": 1
            "3g.20gb": 1

  run.sh : |
    #! /bin/bash

    set -e
    set -x

    CURRENT_MIG_STATE=$(nvidia-smi --query-gpu=mig.mode.current --format=csv,noheader)
    echo "CURRENT MIG STATE:    $CURRENT_MIG_STATE"
    echo "CURRENT MIG MODE:"
    nvidia-mig-parted export

    echo "DESIRED MIG MODE:     $MIG_MODE"
    echo "DESIRED MIG STRATEGY: $MIG_STRATEGY"
    export MIG_PARTED_SELECTED_CONFIG="$MIG_MODE"

    bash /mig-parted/deployments/systemd/service.sh

    sleep +inf
