apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  namespace: {pod_namespace}
spec:
  restartPolicy: Never
  containers:
    - name: mlperf-ssd
      image: "image-registry.openshift-image-registry.svc:5000/default/mlperf:ssd_0.7"
      command:
        - "/bin/bash"
        - "-x"
        - ./my_run_and_time.sh
      env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=5.0"
        - name: DGX_SYSTEM
          value: CUSTOM
{env_values}
      securityContext:
        privileged: true
      resources:
{gpu_resources}
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /data/coco2017
        name: mlperf-data
      - name: config-volume
        mountPath: /workspace/single_stage_detector/my_run_and_time.sh
        readOnly: false
        subPath: my_run_and_time.sh
  volumes:
  - name: mlperf-data
    persistentVolumeClaim:
      claimName: benchmarking-coco-dataset
  - name: dshm
    emptyDir:
      medium: Memory
  - name: config-volume
    configMap:
      defaultMode: 0777
      name: custom-config-script
