apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mpi-osu-image
  namespace: mpi-benchmark
spec:
  output:
    to:
      kind: ImageStreamTag
      name: mpi-bench:osu-bench
  source:
    dockerfile: |2
      FROM mpi-bench:base3

      RUN cd /root \
       && wget https://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.6.3.tar.gz \
       && tar xvf osu-micro-benchmarks-5.6.3.tar.gz \
       && cd osu-micro-benchmarks-5.6.3 \
       && ./configure --prefix=/opt/osu-micro-benchmarks CC=/usr/lib64/openmpi/bin/mpicc LIBS="-L/usr/lib64/openmpi/lib -lmpi -lpthread" \
       && make && make install \
       && cd /root && rm -rf /root/osu-micro-benchmarks-5.6.3
       
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: mpi-bench:base3
    type: Docker
  triggers:
  - type: ConfigChange

