name: Test the generation of test matrices pages

# Controls when the action will run.
# on:
#   pull_request:
#     branches:
#       - master
jobs:
  test-generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate the test matrix 🔧
        run: |
          cd submodules/ci-dashboard/
          export CI_DASHBOARD_DAILYMATRIX_TEST_HISTORY=3
          make matrix_benchmarks
